// Copyright (c) 2025 Ben Swift
// Licensed under CC BY-NC-SA 4.0. See handouts/LICENSE for details.
//
// Shared token rendering for the cutout-family templates.
//
// Imported by tokenized-cutouts.typ (cut-up tokens spread on a table) and
// tokenized-sheets.typ (pre-shuffled per-participant search sheets). Both show
// the same thing --- a next word paired with the previous words that preceded
// it --- so the palette, the hash that assigns colours, and the box/word
// renderers live here rather than being duplicated and left to drift.
//
// The website compiles these templates in the browser too, so this file is
// copied into website/src/templates/ and mapped into the typst.ts virtual
// filesystem alongside them (scripts/copy-cli-templates.ts).

// Gap between a cutout's previous-word boxes and its next word. In em so it
// tracks whatever text size the importing template sets.
#let inter_word_gap = 0.3em

// Two palettes, both generated by Glasbey-style greedy max-min OKLab ΔE
// selection under a minimum hue separation (cli/scripts/generate_palette.ts).
// Each bundles its colours with the hash parameters tuned for that many
// buckets — the two travel together because the bucket count is the modulus,
// so a salt tuned for 30 buckets says nothing about how words scatter across
// 11.
//
// The hue floor is what makes these scannable rather than merely far apart.
// Max-min ΔE on its own reads a lightness step and a hue step as the same
// distance, and a scanning eye does not: the unconstrained palettes put 79%
// and 85% of their tightest pairs' distance on the L axis, which is the axis
// that reads as "that colour again, darker" on a small glyph. They also left
// 113° of the hue wheel empty while stacking three colours inside 5°. Trading
// a little min ΔE for a hue floor buys back the axis that actually pops out.
//
// Each colour is `(color, light)`. When `light` is true (OKLab L > 0.65) the
// renderer pairs the colour with black text on the previous-word box and a
// thin black stroke on the free-standing next word; otherwise white text on
// the box and an unstroked next word.
//
// The `mult`/`salt` pair is chosen by brute-force search over
// (prime <= 1000, salt < 1000003) to maximise how many of the top-30 English
// tokens — punctuation included — land in distinct buckets, tie-broken on
// keeping ".", ",", "?" and "!" apart and on how far down the frequency list
// the first collision falls. The naïve multiplier 31 (Java's String.hashCode
// constant) is a trap: 31 mod 30 = 1 collapses the mod-30 hash into a
// near-sum of codepoints, colliding same-length common words like "it"/"on"
// regardless of salt.
// Regenerate with: node cli/scripts/find_palette_salt.ts --palette-len <n>

// The cutouts palette: 28 chromatic + black + mid-grey = 30 swatches, min
// pairwise OKLab ΔE = 0.121 under an 8° hue floor. That sits in the "clearly
// distinct" range (≥0.10) with headroom for the 0.02–0.05 that CMYK
// conversion, paper colour and ambient light take back. 8° is close to the
// ceiling here: 28 colours cannot all be more than 360/28 ≈ 12.9° apart, and
// the printable gamut runs out at 12°, so the floor is doing what it can.
//
// The grey is luma(113), the sRGB value of the L=0.55 anchor the search seeds:
// it used to be emitted as luma(140), which the search never protected and
// which sat ΔE 0.119 from a desaturated sage green — the grey, not any
// chromatic pair, was the tightest gap in the palette. L is floored at 0.32
// (not 0.20) so no chromatic entry sits close enough to black for CMYK
// compression to merge
// them on paper — an earlier palette had a dark blue at L≈0.275 that printed
// as black. Chroma is floored at 0.08 rather than the script's 0.05: the hue
// floor pushes the search into the thin corners of the gamut, where it would
// otherwise settle for a near-grey lilac that reads as a smudge. The adaptive
// light/dark treatment is what lets it extend to L≈0.92 and so reach 28
// chromatic entries, against ~20 if every fill had to carry white text. At
// the cutouts' 36pt these near-neighbours are still easy to tell apart; the
// sheets palette below exists because at 16pt they aren't.
// Regenerate with:
//   node cli/scripts/generate_palette.ts --n 28 --l-min 0.32 --min-hue-sep 8 --c-min 0.08
#let large-palette = (
  mult: 569,
  salt: 247509,
  // 28/30 top tokens distinct; only "are"/"be" and "?"/"!" collide.
  colors: (
    // Neutrals (always dark enough for white text)
    (color: luma(0), light: false), // black
    (color: luma(113), light: false), // mid grey (OKLab L=0.55)

    // Chromatic (sorted by hue)
    (color: oklch(80.5%, 0.109, 18deg), light: true),
    (color: oklch(62.9%, 0.256, 27deg), light: false),
    (color: oklch(52.9%, 0.180, 36deg), light: false),
    (color: oklch(40.8%, 0.117, 45deg), light: false),
    (color: oklch(62.6%, 0.142, 62deg), light: false),
    (color: oklch(78.8%, 0.170, 71deg), light: true),
    (color: oklch(91.7%, 0.082, 107deg), light: true),
    (color: oklch(79.3%, 0.182, 117deg), light: true),
    (color: oklch(91.9%, 0.234, 126deg), light: true),
    (color: oklch(33.9%, 0.097, 134deg), light: false),
    (color: oklch(67.1%, 0.227, 143deg), light: true),
    (color: oklch(74.9%, 0.080, 157deg), light: true),
    (color: oklch(61.9%, 0.121, 171deg), light: false),
    (color: oklch(44.6%, 0.081, 181deg), light: false),
    (color: oklch(89.4%, 0.154, 189deg), light: true),
    (color: oklch(82.0%, 0.089, 228deg), light: true),
    (color: oklch(72.3%, 0.160, 239deg), light: true),
    (color: oklch(40.0%, 0.124, 253deg), light: false),
    (color: oklch(44.8%, 0.309, 264deg), light: false),
    (color: oklch(60.4%, 0.216, 276deg), light: false),
    (color: oklch(51.0%, 0.130, 287deg), light: false),
    (color: oklch(37.7%, 0.202, 296deg), light: false),
    (color: oklch(50.1%, 0.252, 310deg), light: false),
    (color: oklch(89.0%, 0.081, 319deg), light: true),
    (color: oklch(69.9%, 0.320, 329deg), light: true),
    (color: oklch(32.3%, 0.140, 337deg), light: false),
    (color: oklch(69.8%, 0.128, 346deg), light: true),
    (color: oklch(49.2%, 0.193, 358deg), light: false),
  ),
)

// The search-sheets palette: 6 chromatic + black + grey = 8 swatches, min
// pairwise ΔE = 0.151 on screen and 0.102 on paper. Sheets set their pairs around 16-19pt rather than the cutouts'
// 36pt, and colour discrimination falls off with size: at that scale 30
// swatches read as "some sort of blue" rather than as 30 answers, so scanning
// by colour stops narrowing anything down. Fewer, further-apart colours
// collide more often on the page but each collision is obvious, which is the
// better failure for a page you scan.
//
// Eight rather than the eleven this used to hold, because nobody is
// discriminating eleven colours here. Each participant holds ONE sheet of
// ~50 pairs, so a colour never has to separate the whole corpus --- only the
// handful of pairs in front of one pair of eyes. Eight buckets put ~6 pairs
// of each colour on a sheet, which is all "it's a green one" has to narrow
// down before someone reads the token.
//
// Generated differently from the palette above, and this is the substantive
// difference between them. The large palette is a free max-min search that
// gets named afterwards, by hand, against the xkcd survey --- which is how it
// ended up needing "ochre" and "wine", words chosen because they were the
// nearest available, not because a room would reach for them. Here the words
// come first: every swatch is pinned to a colour word's survey centroid, and
// the search picks the eight words whose printable colours sit furthest
// apart. Nameability is a hard constraint rather than a post-hoc label,
// because the name is how a colour gets used --- "who has _cat_? it's a green
// one" only works if the room agrees on which swatch "green" means.
//
// What the contrast floor costs: at 4.5:1 against white, yellow (ΔE 0.41 from
// its centroid), lime (0.36), tan (0.20), mustard (0.20), turquoise (0.18),
// pink (0.17) and orange (0.12) all have to darken so far that the word stops
// describing what prints --- a printable "yellow" is an olive. They are
// dropped rather than renamed. Of the eight kept, seven print at their survey
// centroid exactly; grey moves 0.098 and green 0.112, those two being the
// words doing real work to stay printable.
//
// Which eight was decided on paper, not on screen, and the two answers differ.
// OKLab says how different two colours look; it does not know which colours a
// press can make, and sRGB's vivid blues, greens and purples are outside CMYK.
// Round-tripping through a profile compresses them toward the gamut boundary
// and closes the gaps: the first version of this palette held teal instead of
// grey and measured a comfortable 0.130 in sRGB, but green/teal printed at
// 0.093 on uncoated stock and 0.079 on newsprint --- under the 0.10 this file
// calls clearly distinct. Swapping teal for grey costs nothing anyone will
// notice (it also buys the plainer word) and lifts the worst case to 0.102 on
// every profile checked. Screen min ΔE is 0.151; the binding pair on paper is
// red/magenta.
//
// No orange, which is the obvious question given how basic a colour word it
// is. At the contrast floor a printable orange is #d24802, a dark burnt one,
// and it prints ΔE 0.046--0.059 from red: you can have orange or red, not
// both. Trading red away for it (orange, brown, green, blue, purple, magenta,
// black, grey) does measure 0.104 against this set's 0.102, but 0.002 is not
// worth giving up the most basic colour word in the language, and it leaves
// orange and brown adjacent as names as well as as hues.
//
// Navy is the cautionary one, and confirms what the large palette's comment
// above says about dark blues: black/navy prints at ΔE 0.045 on newsprint.
// Nothing in sRGB warns you.
//
// Regenerate, then re-check on paper --- the second step is not optional,
// because the first one cannot see the press:
//   node cli/scripts/generate_palette.ts --nameable --n 8 \
//     --min-white-contrast 4.5 --dump-candidates > /tmp/candidates.csv
//   cli/scripts/check_palette_print.py /tmp/candidates.csv --n 8
//
// Every entry clears 4.5:1 WCAG contrast against white, so the next token is
// dark enough to read as plain coloured text on paper and needs no stroke to
// prop it up. It also means every box carries white text.
//
// The names are the generator's own, not applied afterwards, so re-running it
// re-derives them; there is nothing to re-name by hand.
#let compact-palette = (
  mult: 7,
  salt: 14564,
  // 8/8 buckets filled by the 8 most frequent tokens, all four punctuation
  // marks distinct, first collision only at the 9th --- the best an 8-bucket
  // hash can do.
  colors: (
    // Neutrals
    (color: luma(0), light: false, name: "black"),
    (color: oklch(56.9%, 0.014, 46deg), light: false, name: "grey"),

    // Chromatic (sorted by hue)
    (color: oklch(57.9%, 0.238, 29deg), light: false, name: "red"),
    (color: oklch(38.6%, 0.089, 62deg), light: false, name: "brown"),
    (color: oklch(55.1%, 0.185, 142deg), light: false, name: "green"),
    (color: oklch(47.2%, 0.241, 263deg), light: false, name: "blue"),
    (color: oklch(45.2%, 0.195, 316deg), light: false, name: "purple"),
    (color: oklch(53.4%, 0.221, 353deg), light: false, name: "magenta"),
  ),
)

// Brand gold, matches the tool-trigger word foreground and the favicon dots.
#let brand-gold = rgb("#d4a017")

// The project typeface, as used on the website. Everything that is the
// project talking --- instructions, footers, the word mark --- is set in it.
// The tokens themselves stay Libertinus Serif: they are the thing being read
// closely, at a glance, in colour, and a serif at 19pt does that better than
// any UI sans. So the two faces divide by role, not by page.
#let brand-font = "Public Sans"

// The token typeface, pinned by the renderers below rather than inherited
// from the surrounding page. Both templates set it as the document font and
// then switch to `brand-font` for their instructions page, which used to take
// the worked example and the inline pair chips with it: the tokens quoted in
// the brief were set in a face nothing else in the deal uses, so they did not
// look like the pairs they were explaining. Pinning it here is what makes the
// comments in both templates true --- a token renders the same wherever it is
// placed, and the two faces divide by role rather than by page.
#let token-font = ("Libertinus Serif", "Noto Serif CJK SC")

// The brand mark, as a horizontal lockup of the 4x4 bit grid and the title
// (see the "Designing the LLMs Unplugged brand mark" news post). Generated by
// website/scripts/generate-logo-svgs.ts into website/public/; copied here so
// the templates can reach it by relative path, the way the CLI's other SVG
// assets are. Re-copy after regenerating.
//
// The "light" variant is the one for paper: its title paths are dark
// (#1a1a1a) for light surfaces, where the default variant's are not. The
// wordmark is baked to outlines, so this renders identically whether or not
// Public Sans is installed --- which matters for the in-browser compiler,
// where a missing face fails silently.
#let brand-lockup(width: 32mm) = image("lockup-light.svg", width: width)

// A tool-trigger word: black highlight with bold uppercase gold text. Used
// for tokens flagged `is_tool: true` so a trigger like VOTE stays visually
// unambiguous even when the corpus contains the same string as a regular word.
// Uses `highlight` rather than `box` so the baseline aligns with surrounding
// inline text.
#let tool-trigger-word(name, dimmed: false) = {
  let bg = if dimmed { luma(220) } else { black }
  let fg = if dimmed { luma(140) } else { brand-gold }
  highlight(
    fill: bg,
    stroke: (paint: fg, thickness: 1pt),
    extent: 0.1em,
    radius: 2pt,
    text(font: token-font, fill: fg, weight: "bold", upper(name)),
  )
}

// Build the token renderers against a palette. Returns a dictionary the
// importing template destructures, e.g.
//   #let (render-cutout, coloured-word, ..) = renderers(palette: compact-palette)
// A factory rather than plain top-level functions because the palette has to
// reach `entry-for` at the bottom of the call chain, and threading a `palette:`
// argument through every renderer and every call site would put it in the way
// of the thing each call is actually saying.
#let renderers(palette: large-palette) = {
  // Hash a word to a palette entry, returning the `(color, light)` record:
  // callers unpack `.color` for the swatch and `.light` for the adaptive
  // text/stroke decision. Hashing (rather than assigning in order) is what
  // makes the same word take the same colour wherever it appears, in a
  // previous-word box or as a free-standing next word. The CLI canonicalises
  // casing per corpus before emitting the JSON, so the same word always
  // arrives here as the same string — no need to case-fold again.
  let entry-for(t) = {
    let h = palette.salt
    for c in t.codepoints() {
      h = calc.rem(h * palette.mult + str.to-unicode(c), 1000003)
    }
    palette.colors.at(calc.rem(h, palette.colors.len()))
  }

  // The box treatment itself, given a palette entry and the content to set in
  // it: the entry's colour as fill, with black or white text depending on its
  // `light` flag (black on light fills, white on dark). When `dimmed` is true
  // (discarded source token) the box is grey with white text — the poor
  // contrast is intentional fade-out. Uses `highlight` rather than `box` so
  // the box's baseline aligns with the surrounding free-standing word.
  //
  // Split out from `previous-word-box` because the sheets' colour key boxes a
  // colour's *name* in that colour, which is the same swatch with the hash
  // step skipped — a name has no reason to hash to the colour it names.
  let word-box(entry, body, dimmed: false) = {
    let fill = if dimmed { luma(180) } else { entry.color }
    let text-fill = if dimmed or not entry.light { white } else { black }
    highlight(
      fill: fill,
      extent: 0.1em,
      radius: 2pt,
      text(font: token-font, fill: text-fill, weight: "bold", body),
    )
  }

  // A coloured box for a previous word, in the colour that word hashes to.
  let previous-word-box(t, dimmed: false) = word-box(
    entry-for(t),
    t,
    dimmed: dimmed,
  )

  // A free-standing word in its assigned colour. Bold, matching the weight of
  // the previous-word boxes it sits beside: as plain text it is the only mark
  // on the page carrying no fill behind it, and at regular weight it reads as
  // an afterthought rather than as the answer. The deck theme's
  // `.cutout-next-word` does the same for the same reason.
  //
  // Light entries (OKLab L > 0.65) also get a thin black stroke so they're
  // readable on white paper; dark entries are rendered flat, so a palette with
  // no light entries never strokes anything. Dimmed words are mid-grey with no
  // stroke.
  let coloured-word(t, dimmed: false) = {
    let entry = entry-for(t)
    let fill = if dimmed { luma(160) } else { entry.color }
    let stroke = if not dimmed and entry.light { 0.5pt + black } else { none }
    text(font: token-font, fill: fill, stroke: stroke, weight: "bold", t)
  }

  // Pick the right renderer for a token's next-word slot. Tool-trigger tokens
  // get a trailing period (in normal next-token styling) on the same cutout,
  // so the agentic loop "call tool, write its response, close with a period"
  // reads as one physical piece of paper rather than two coordinated cutouts.
  let next-word(token, dimmed: false) = if token.at(
    "is_tool",
    default: false,
  ) {
    (
      tool-trigger-word(token.text, dimmed: dimmed)
        + h(inter_word_gap)
        + coloured-word(".", dimmed: dimmed)
    )
  } else {
    coloured-word(token.text, dimmed: dimmed)
  }

  // Render a cutout's previous-word boxes followed by its next word, inline.
  let render-cutout(token, dimmed: false) = {
    // `previous_words` is omitted from the JSON when empty (the leading tokens
    // of a text have no context), so read it defensively --- such a token
    // renders as its next word alone.
    let prev_words = token.at("previous_words", default: ())
    let parts = prev_words.map(t => previous-word-box(
      t,
      dimmed: dimmed,
    ))
    parts.push(next-word(token, dimmed: dimmed))
    parts.join(h(inter_word_gap))
  }

  (
    entry-for: entry-for,
    word-box: word-box,
    previous-word-box: previous-word-box,
    coloured-word: coloured-word,
    next-word: next-word,
    render-cutout: render-cutout,
  )
}

// Derive n from the first token that has previous words recorded. Both
// templates need it to phrase their instructions ("the last word" vs "the
// last 2 words"), and neither is told n directly.
#let derive-n(tokens) = {
  let found = tokens.find(t => (
    "previous_words" in t and t.previous_words.len() > 0
  ))
  if found != none { found.previous_words.len() + 1 } else { 2 }
}
