// Shared token rendering for the cutout-family templates.
//
// Imported by tokenized-cutouts.typ (cut-up tokens spread on a table) and
// tokenized-sheets.typ (pre-shuffled per-participant search sheets). Both show
// the same thing --- a next word paired with the previous words that preceded
// it --- so the palette, the hash that assigns colours, and the box/word
// renderers live here rather than being duplicated and left to drift.
//
// The website compiles these templates in the browser too, so this file is
// copied into website/src/templates/ and mapped into the typst.ts virtual
// filesystem alongside them (scripts/copy-cli-templates.ts).

// Gap between a cutout's previous-word boxes and its next word. In em so it
// tracks whatever text size the importing template sets.
#let inter_word_gap = 0.3em

// Palette of perceptually distinct colours, generated by Glasbey-style
// greedy max-min OKLab ΔE selection. N=28 chromatic + black + mid-grey =
// 30 swatches. Min pairwise OKLab ΔE = 0.137, which sits in the "clearly
// distinct" range (≥0.10; print reproduction loses 0.02–0.05 of ΔE through
// CMYK conversion, paper colour, and ambient light, so we want headroom).
// Black and mid-grey are seeded as search anchors so chromatic colours
// can't collapse onto the greyscale axis. L is floored at 0.32 (not 0.20)
// so no chromatic entry sits close enough to black that CMYK compression
// can merge them on paper — earlier palettes had a dark blue at L≈0.275
// that read as black in print.
// Words hash-assigned to a palette index, so the same word always takes
// the same colour whether in a previous-word box or as a free-standing
// next word. Each entry is `(color, light)`: when `light` is true (OKLab
// L > 0.65) the renderer pairs the colour with black text on the box and
// a thin black stroke on the free-standing word; otherwise white text on
// the box and an unstroked free-standing word. This adaptive treatment is
// what lets the palette extend up to L≈0.92 and so reach 28 chromatic
// entries (vs ~20 when everything must read with white text).
// Regenerate with: node cli/scripts/generate_palette.ts --n 28 --l-min 0.32
#let palette = (
  // Neutrals (always dark enough for white text)
  (color: luma(0), light: false), // black
  (color: luma(140), light: false), // mid grey

  // Chromatic (sorted by hue)
  (color: oklch(32.4%, 0.082, 24deg), light: false),
  (color: oklch(62.9%, 0.256, 27deg), light: false),
  (color: oklch(42.8%, 0.174, 29deg), light: false),
  (color: oklch(62.3%, 0.142, 62deg), light: false),
  (color: oklch(78.0%, 0.166, 72deg), light: true),
  (color: oklch(43.2%, 0.086, 84deg), light: false),
  (color: oklch(91.9%, 0.096, 93deg), light: true),
  (color: oklch(91.9%, 0.234, 126deg), light: true),
  (color: oklch(48.5%, 0.164, 142deg), light: false),
  (color: oklch(67.1%, 0.227, 143deg), light: true),
  (color: oklch(32.2%, 0.098, 143deg), light: false),
  (color: oklch(75.9%, 0.078, 151deg), light: true),
  (color: oklch(81.2%, 0.214, 151deg), light: true),
  (color: oklch(62.8%, 0.118, 174deg), light: false),
  (color: oklch(90.4%, 0.149, 187deg), light: true),
  (color: oklch(73.7%, 0.158, 236deg), light: true),
  (color: oklch(42.0%, 0.131, 254deg), light: false),
  (color: oklch(44.8%, 0.309, 264deg), light: false),
  (color: oklch(58.9%, 0.192, 268deg), light: false),
  (color: oklch(40.1%, 0.227, 288deg), light: false),
  (color: oklch(67.6%, 0.212, 304deg), light: true),
  (color: oklch(51.3%, 0.259, 308deg), light: false),
  (color: oklch(32.1%, 0.151, 320deg), light: false),
  (color: oklch(46.8%, 0.124, 324deg), light: false),
  (color: oklch(90.4%, 0.084, 328deg), light: true),
  (color: oklch(69.9%, 0.320, 329deg), light: true),
  (color: oklch(71.1%, 0.118, 346deg), light: true),
  (color: oklch(54.4%, 0.227, 349deg), light: false),
)

// Hash a word to a palette entry. Returns the `(color, light)` record;
// callers unpack `.color` for the swatch and `.light` for the adaptive
// text/stroke decision. The CLI canonicalises casing per corpus before
// emitting the JSON, so the same word always arrives as the same string
// here — no need to case-fold again.
// Multiplier 569 and initial salt 247509 were chosen by brute-force
// search over (prime <= 1000, salt < 1000003) pairs to maximise the
// number of top-30 English tokens (including the four kept punctuation
// marks ".", ",", "?", "!") that land in distinct palette buckets. This
// combination achieves 28/30 distinct: the only collisions are "are"/"be"
// and "?"/"!". The naïve choice of multiplier 31 — Java's String.hashCode
// constant — caps out at ~15 because 31 mod 30 = 1 collapses the mod-30
// hash into a near-sum, colliding same-length common words like "it"/"on"
// and "of"/"at" regardless of salt.
// Regenerate with: node cli/scripts/find_palette_salt.ts
#let entry-for(t) = {
  let h = 247509
  for c in t.codepoints() {
    h = calc.rem(h * 569 + str.to-unicode(c), 1000003)
  }
  palette.at(calc.rem(h, palette.len()))
}

// A coloured box for a previous word: word's assigned colour as fill, with
// black or white text depending on the entry's `light` flag (black on light
// fills, white on dark fills). When `dimmed` is true (discarded source token)
// the box is rendered in grey with white text — the poor contrast is
// intentional fade-out. Uses `highlight` rather than `box` so the previous
// word's baseline aligns with the surrounding free-standing word.
#let previous-word-box(t, dimmed: false) = {
  let entry = entry-for(t)
  let fill = if dimmed { luma(180) } else { entry.color }
  let text-fill = if dimmed or not entry.light { white } else { black }
  highlight(
    fill: fill,
    extent: 0.1em,
    radius: 2pt,
    text(fill: text-fill, weight: "bold", t),
  )
}

// A free-standing word in its assigned colour. Light entries (OKLab L > 0.65)
// get a thin black stroke so they're readable as text on white paper; dark
// entries are rendered flat. Dimmed words are mid-grey with no stroke.
#let coloured-word(t, dimmed: false) = {
  let entry = entry-for(t)
  let fill = if dimmed { luma(160) } else { entry.color }
  let stroke = if not dimmed and entry.light { 0.5pt + black } else { none }
  text(fill: fill, stroke: stroke, t)
}

// Brand gold, matches the tool-trigger word foreground and the favicon dots.
#let brand-gold = rgb("#d4a017")

// A tool-trigger word: black highlight with bold uppercase gold text. Used
// for tokens flagged `is_tool: true` so a trigger like VOTE stays visually
// unambiguous even when the corpus contains the same string as a regular word.
// Uses `highlight` rather than `box` so the baseline aligns with surrounding
// inline text.
#let tool-trigger-word(name, dimmed: false) = {
  let bg = if dimmed { luma(220) } else { black }
  let fg = if dimmed { luma(140) } else { brand-gold }
  highlight(
    fill: bg,
    stroke: (paint: fg, thickness: 1pt),
    extent: 0.1em,
    radius: 2pt,
    text(fill: fg, weight: "bold", upper(name)),
  )
}

// Pick the right renderer for a token's next-word slot. Tool-trigger tokens
// get a trailing period (in normal next-token styling) on the same cutout, so
// the agentic loop "call tool, write its response, close with a period" reads
// as one physical piece of paper rather than two coordinated cutouts.
#let next-word(token, dimmed: false) = if token.at("is_tool", default: false) {
  (
    tool-trigger-word(token.text, dimmed: dimmed)
      + h(inter_word_gap)
      + coloured-word(".", dimmed: dimmed)
  )
} else {
  coloured-word(token.text, dimmed: dimmed)
}

// Render a cutout's previous-word boxes followed by its next word, all inline.
#let render-cutout(token, dimmed: false) = {
  // `previous_words` is omitted from the JSON when empty (the leading tokens
  // of a text have no context), so read it defensively --- such a token
  // renders as its next word alone.
  let prev_words = token.at("previous_words", default: ())
  let parts = prev_words.map(t => previous-word-box(
    t,
    dimmed: dimmed,
  ))
  parts.push(next-word(token, dimmed: dimmed))
  parts.join(h(inter_word_gap))
}

// Derive n from the first token that has previous words recorded. Both
// templates need it to phrase their instructions ("the last word" vs "the
// last 2 words"), and neither is told n directly.
#let derive-n(tokens) = {
  let found = tokens.find(t => (
    "previous_words" in t and t.previous_words.len() > 0
  ))
  if found != none { found.previous_words.len() + 1 } else { 2 }
}
