// Shared token rendering for the cutout-family templates.
//
// Imported by tokenized-cutouts.typ (cut-up tokens spread on a table) and
// tokenized-sheets.typ (pre-shuffled per-participant search sheets). Both show
// the same thing --- a next word paired with the previous words that preceded
// it --- so the palette, the hash that assigns colours, and the box/word
// renderers live here rather than being duplicated and left to drift.
//
// The website compiles these templates in the browser too, so this file is
// copied into website/src/templates/ and mapped into the typst.ts virtual
// filesystem alongside them (scripts/copy-cli-templates.ts).

// Gap between a cutout's previous-word boxes and its next word. In em so it
// tracks whatever text size the importing template sets.
#let inter_word_gap = 0.3em

// Two palettes, both generated by Glasbey-style greedy max-min OKLab ΔE
// selection (cli/scripts/generate_palette.ts). Each bundles its colours with
// the hash parameters tuned for that many buckets — the two travel together
// because the bucket count is the modulus, so a salt tuned for 30 buckets
// says nothing about how words scatter across 12.
//
// Each colour is `(color, light)`. When `light` is true (OKLab L > 0.65) the
// renderer pairs the colour with black text on the previous-word box and a
// thin black stroke on the free-standing next word; otherwise white text on
// the box and an unstroked next word.
//
// The `mult`/`salt` pair is chosen by brute-force search over
// (prime <= 1000, salt < 1000003) to maximise how many of the top-30 English
// tokens — punctuation included — land in distinct buckets, tie-broken on
// keeping ".", ",", "?" and "!" apart and on how far down the frequency list
// the first collision falls. The naïve multiplier 31 (Java's String.hashCode
// constant) is a trap: 31 mod 30 = 1 collapses the mod-30 hash into a
// near-sum of codepoints, colliding same-length common words like "it"/"on"
// regardless of salt.
// Regenerate with: node cli/scripts/find_palette_salt.ts --palette-len <n>

// The cutouts palette: 28 chromatic + black + mid-grey = 30 swatches, min
// pairwise OKLab ΔE = 0.137. That sits in the "clearly distinct" range
// (≥0.10) with headroom for the 0.02–0.05 that CMYK conversion, paper colour
// and ambient light take back. The grey is luma(113), the sRGB value of the
// L=0.55 anchor the search seeds: it used to be emitted as luma(140), which
// the search never protected and which sat ΔE 0.119 from a desaturated sage
// green — the grey, not any chromatic pair, was the tightest gap in the
// palette. L is floored at 0.32 (not 0.20) so no
// chromatic entry sits close enough to black for CMYK compression to merge
// them on paper — an earlier palette had a dark blue at L≈0.275 that printed
// as black. The adaptive light/dark treatment is what lets it extend to
// L≈0.92 and so reach 28 chromatic entries, against ~20 if every fill had to
// carry white text. At the cutouts' 36pt these near-neighbours are still easy
// to tell apart; the sheets palette below exists because at 11pt they aren't.
// Regenerate with: node cli/scripts/generate_palette.ts --n 28 --l-min 0.32
#let large-palette = (
  mult: 569,
  salt: 247509,
  // 28/30 top tokens distinct; only "are"/"be" and "?"/"!" collide.
  colors: (
    // Neutrals (always dark enough for white text)
    (color: luma(0), light: false), // black
    (color: luma(113), light: false), // mid grey (OKLab L=0.55)

    // Chromatic (sorted by hue)
    (color: oklch(32.4%, 0.082, 24deg), light: false),
    (color: oklch(62.9%, 0.256, 27deg), light: false),
    (color: oklch(42.8%, 0.174, 29deg), light: false),
    (color: oklch(62.3%, 0.142, 62deg), light: false),
    (color: oklch(78.0%, 0.166, 72deg), light: true),
    (color: oklch(43.2%, 0.086, 84deg), light: false),
    (color: oklch(91.9%, 0.096, 93deg), light: true),
    (color: oklch(91.9%, 0.234, 126deg), light: true),
    (color: oklch(48.5%, 0.164, 142deg), light: false),
    (color: oklch(67.1%, 0.227, 143deg), light: true),
    (color: oklch(32.2%, 0.098, 143deg), light: false),
    (color: oklch(75.9%, 0.078, 151deg), light: true),
    (color: oklch(81.2%, 0.214, 151deg), light: true),
    (color: oklch(62.8%, 0.118, 174deg), light: false),
    (color: oklch(90.4%, 0.149, 187deg), light: true),
    (color: oklch(73.7%, 0.158, 236deg), light: true),
    (color: oklch(42.0%, 0.131, 254deg), light: false),
    (color: oklch(44.8%, 0.309, 264deg), light: false),
    (color: oklch(58.9%, 0.192, 268deg), light: false),
    (color: oklch(40.1%, 0.227, 288deg), light: false),
    (color: oklch(67.6%, 0.212, 304deg), light: true),
    (color: oklch(51.3%, 0.259, 308deg), light: false),
    (color: oklch(32.1%, 0.151, 320deg), light: false),
    (color: oklch(46.8%, 0.124, 324deg), light: false),
    (color: oklch(90.4%, 0.084, 328deg), light: true),
    (color: oklch(69.9%, 0.320, 329deg), light: true),
    (color: oklch(71.1%, 0.118, 346deg), light: true),
    (color: oklch(54.4%, 0.227, 349deg), light: false),
  ),
)

// The search-sheets palette: 10 chromatic + black + mid-grey = 12 swatches,
// min pairwise ΔE = 0.180. Sheets set their entries around 11pt rather than
// the cutouts' 36pt, and colour discrimination falls off with size: at that
// scale 30 swatches read as "some sort of blue" rather than as 30 answers, so
// scanning by colour stops narrowing anything down. Fewer, further-apart
// colours collide more often on the page but each collision is obvious,
// which is the better failure for a page you scan.
//
// Every entry additionally clears a 4.5:1 WCAG contrast ratio against white
// (`--min-white-contrast 4.5`), which is a stronger constraint than the
// L ≤ 0.65 that `light: false` records. So on sheets the next word is dark
// enough to read as plain coloured text on the paper, and needs no stroke to
// prop it up — a 0.5pt outline that reads as a crisp edge at 36pt just fills
// in the counters at 11pt. It also means every box carries white text, so
// there is no mid-lightness fill left wearing hard-to-read black.
// Regenerate with:
//   node cli/scripts/generate_palette.ts --n 10 --min-white-contrast 4.5
#let compact-palette = (
  mult: 17,
  salt: 2028,
  // 12/12 buckets filled by the 12 most frequent tokens, all four punctuation
  // marks distinct, first collision only at the 13th — the best a 12-bucket
  // hash can do.
  colors: (
    // Neutrals
    (color: luma(0), light: false), // black
    (color: luma(113), light: false), // mid grey (OKLab L=0.55)

    // Chromatic (sorted by hue)
    (color: oklch(59.7%, 0.243, 29deg), light: false),
    (color: oklch(40.9%, 0.165, 29deg), light: false),
    (color: oklch(54.9%, 0.185, 142deg), light: false),
    (color: oklch(32.2%, 0.098, 143deg), light: false),
    (color: oklch(41.7%, 0.129, 255deg), light: false),
    (color: oklch(44.8%, 0.309, 264deg), light: false),
    (color: oklch(57.8%, 0.186, 277deg), light: false),
    (color: oklch(60.8%, 0.297, 316deg), light: false),
    (color: oklch(32.1%, 0.151, 320deg), light: false),
    (color: oklch(50.6%, 0.216, 344deg), light: false),
  ),
)

// Brand gold, matches the tool-trigger word foreground and the favicon dots.
#let brand-gold = rgb("#d4a017")

// A tool-trigger word: black highlight with bold uppercase gold text. Used
// for tokens flagged `is_tool: true` so a trigger like VOTE stays visually
// unambiguous even when the corpus contains the same string as a regular word.
// Uses `highlight` rather than `box` so the baseline aligns with surrounding
// inline text.
#let tool-trigger-word(name, dimmed: false) = {
  let bg = if dimmed { luma(220) } else { black }
  let fg = if dimmed { luma(140) } else { brand-gold }
  highlight(
    fill: bg,
    stroke: (paint: fg, thickness: 1pt),
    extent: 0.1em,
    radius: 2pt,
    text(fill: fg, weight: "bold", upper(name)),
  )
}

// Build the token renderers against a palette. Returns a dictionary the
// importing template destructures, e.g.
//   #let (render-cutout, coloured-word, ..) = renderers(palette: compact-palette)
// A factory rather than plain top-level functions because the palette has to
// reach `entry-for` at the bottom of the call chain, and threading a `palette:`
// argument through every renderer and every call site would put it in the way
// of the thing each call is actually saying.
//
// `bold-next` sets the weight of the free-standing next word. The cutouts
// leave it regular: at 36pt the colour alone separates it from its boxed
// context words. Sheets set it bold to match the weight of those boxes,
// because at 11pt a regular-weight coloured word is the lightest mark on a
// dense page and reads as an afterthought rather than as the answer.
#let renderers(palette: large-palette, bold-next: false) = {
  // Hash a word to a palette entry, returning the `(color, light)` record:
  // callers unpack `.color` for the swatch and `.light` for the adaptive
  // text/stroke decision. Hashing (rather than assigning in order) is what
  // makes the same word take the same colour wherever it appears, in a
  // previous-word box or as a free-standing next word. The CLI canonicalises
  // casing per corpus before emitting the JSON, so the same word always
  // arrives here as the same string — no need to case-fold again.
  let entry-for(t) = {
    let h = palette.salt
    for c in t.codepoints() {
      h = calc.rem(h * palette.mult + str.to-unicode(c), 1000003)
    }
    palette.colors.at(calc.rem(h, palette.colors.len()))
  }

  // A coloured box for a previous word: the word's assigned colour as fill,
  // with black or white text depending on the entry's `light` flag (black on
  // light fills, white on dark). When `dimmed` is true (discarded source
  // token) the box is grey with white text — the poor contrast is intentional
  // fade-out. Uses `highlight` rather than `box` so the previous word's
  // baseline aligns with the surrounding free-standing word.
  let previous-word-box(t, dimmed: false) = {
    let entry = entry-for(t)
    let fill = if dimmed { luma(180) } else { entry.color }
    let text-fill = if dimmed or not entry.light { white } else { black }
    highlight(
      fill: fill,
      extent: 0.1em,
      radius: 2pt,
      text(fill: text-fill, weight: "bold", t),
    )
  }

  // A free-standing word in its assigned colour. Light entries (OKLab L >
  // 0.65) get a thin black stroke so they're readable as text on white paper;
  // dark entries are rendered flat, so a palette with no light entries never
  // strokes anything. Dimmed words are mid-grey with no stroke.
  let coloured-word(t, dimmed: false) = {
    let entry = entry-for(t)
    let fill = if dimmed { luma(160) } else { entry.color }
    let stroke = if not dimmed and entry.light { 0.5pt + black } else { none }
    text(
      fill: fill,
      stroke: stroke,
      weight: if bold-next { "bold" } else { "regular" },
      t,
    )
  }

  // Pick the right renderer for a token's next-word slot. Tool-trigger tokens
  // get a trailing period (in normal next-token styling) on the same cutout,
  // so the agentic loop "call tool, write its response, close with a period"
  // reads as one physical piece of paper rather than two coordinated cutouts.
  let next-word(token, dimmed: false) = if token.at(
    "is_tool",
    default: false,
  ) {
    (
      tool-trigger-word(token.text, dimmed: dimmed)
        + h(inter_word_gap)
        + coloured-word(".", dimmed: dimmed)
    )
  } else {
    coloured-word(token.text, dimmed: dimmed)
  }

  // Render a cutout's previous-word boxes followed by its next word, inline.
  let render-cutout(token, dimmed: false) = {
    // `previous_words` is omitted from the JSON when empty (the leading tokens
    // of a text have no context), so read it defensively --- such a token
    // renders as its next word alone.
    let prev_words = token.at("previous_words", default: ())
    let parts = prev_words.map(t => previous-word-box(
      t,
      dimmed: dimmed,
    ))
    parts.push(next-word(token, dimmed: dimmed))
    parts.join(h(inter_word_gap))
  }

  (
    entry-for: entry-for,
    previous-word-box: previous-word-box,
    coloured-word: coloured-word,
    next-word: next-word,
    render-cutout: render-cutout,
  )
}

// Derive n from the first token that has previous words recorded. Both
// templates need it to phrase their instructions ("the last word" vs "the
// last 2 words"), and neither is told n directly.
#let derive-n(tokens) = {
  let found = tokens.find(t => (
    "previous_words" in t and t.previous_words.len() > 0
  ))
  if found != none { found.previous_words.len() + 1 } else { 2 }
}
