// PDFs (booklets, cutouts, sheets, worksheets, presenter guides) are served
// from a Tigris bucket fronted by pdf.llmsunplugged.org, not from this site's
// public/ directory.
//
// They used to ship inside the GitHub Pages artifact: the largest category
// there, and the only unbounded one --- each regeneration committed a fresh
// multi-MB blob, permanently growing .git (490 MB of the pack was superseded
// PDF revisions). ops/bucket-sync.py documents the bucket and owns uploads.
//
// pdf-manifest.json is the committed record of what the bucket holds
// (regenerated by `ops/bucket-sync.py manifest` after every upload). It is
// what makes bucket links checkable at build time: UsingTheSlides gates its
// presenter-guide links on it, and the build's PDF link check verifies every
// pdf.llmsunplugged.org href against it instead of the filesystem.
import manifest from "../data/pdf-manifest.json";

export const PDF_BASE = "https://pdf.llmsunplugged.org";

const keys = new Set<string>(manifest);

export const pdfUrl = (key: string): string => `${PDF_BASE}/${key}`;

export const hasPdf = (key: string): boolean => keys.has(key);
