import { readFileSync } from "node:fs";
import { join } from "node:path";
import { describe, expect, it } from "vitest";

// The in-browser Typst export (src/lib/typstCompiler.ts) renders Chinese by
// preloading these locally bundled subsets into the compiler's font book. They
// are checked-in binaries generated by scripts/subset-cjk-fonts.py; this guards
// against them going missing, empty, or accidentally un-subset (the full Noto
// CJK faces are ~20 MB each). They must stay uncompressed OTF --- Typst ignores
// woff2 --- so we also assert the CFF/OTTO signature.
const FONTS = [
  {
    name: "NotoSerifCJKsc-Regular-subset.otf",
    // Serif carries more glyph detail than sans, so it is the larger of the two.
    minKB: 1600,
    maxKB: 2800,
  },
  {
    name: "NotoSansCJKsc-Regular-subset.otf",
    minKB: 1100,
    maxKB: 2100,
  },
];

const FONT_DIR = join(process.cwd(), "src/assets/fonts");

// CFF-flavoured OpenType files start with the ASCII tag "OTTO" (0x4F54544F). A
// woff2 (signature "wOF2") slipping back in would not be parsed by Typst.
const OTTO_SIGNATURE = "OTTO";

describe("bundled CJK font subsets", () => {
  for (const font of FONTS) {
    describe(font.name, () => {
      const data = readFileSync(join(FONT_DIR, font.name));

      it("is an uncompressed CFF OpenType file", () => {
        expect(data.subarray(0, 4).toString("latin1")).toBe(OTTO_SIGNATURE);
      });

      it("is subset to a sane size (neither empty nor the full font)", () => {
        const sizeKB = data.byteLength / 1024;
        expect(sizeKB).toBeGreaterThan(font.minKB);
        expect(sizeKB).toBeLessThan(font.maxKB);
      });
    });
  }
});
