import { readFileSync } from "node:fs";
import { join } from "node:path";
import { describe, expect, it } from "vitest";
import { buildBigramModel, getBigrams, getVocabulary, parseTokens } from "../src/lib/tokens";

describe("parseTokens", () => {
  it("splits words on whitespace", () => {
    expect(parseTokens("the cat sat")).toEqual(["the", "cat", "sat"]);
  });

  it("lowercases words that appear with mixed capitalisation", () => {
    expect(parseTokens("Hello world. hello again.")).toEqual([
      "hello",
      "world",
      ".",
      "hello",
      "again",
      ".",
    ]);
  });

  it("preserves a consistent capitalisation (canonical casing)", () => {
    expect(parseTokens("Sally met Sally")).toEqual(["Sally", "met", "Sally"]);
  });

  it("preserves I and its contractions", () => {
    expect(parseTokens("I think I'm fine")).toEqual(["I", "think", "I'm", "fine"]);
  });

  it("keeps punctuation as separate tokens", () => {
    expect(parseTokens("the cat sat.")).toEqual(["the", "cat", "sat", "."]);
    expect(parseTokens("hello, world.")).toEqual(["hello", ",", "world", "."]);
  });

  it("keeps the full default single-punctuation set", () => {
    expect(parseTokens("Hello, world. How are you? Yes; right: now!")).toEqual([
      "Hello",
      ",",
      "world",
      ".",
      "How",
      "are",
      "you",
      "?",
      "Yes",
      ";",
      "right",
      ":",
      "now",
      "!",
    ]);
  });

  it("strips paired punctuation (quotes, brackets, em-dashes)", () => {
    expect(parseTokens('"Quoted text" (parenthetical)---aside')).toEqual([
      "Quoted",
      "text",
      "parenthetical",
      "aside",
    ]);
  });

  it("keeps common words that look like roman numerals", () => {
    expect(parseTokens("did mix the civil dim mill")).toEqual([
      "did",
      "mix",
      "the",
      "civil",
      "dim",
      "mill",
    ]);
  });

  it("filters chapter-style roman numerals", () => {
    expect(parseTokens("chapter iv section xii")).toEqual(["chapter", "section"]);
  });

  it("handles multiple sentences", () => {
    expect(parseTokens("I sat. the cat sat.")).toEqual(["I", "sat", ".", "the", "cat", "sat", "."]);
  });

  it("returns empty array for empty input", () => {
    expect(parseTokens("")).toEqual([]);
  });

  it("filters out numeric tokens", () => {
    expect(parseTokens("chapter 1 the")).toEqual(["chapter", "the"]);
  });

  it("normalises curly apostrophes", () => {
    expect(parseTokens("I\u2019m")).toEqual(["I'm"]);
  });

  it("strips leading apostrophes from words", () => {
    expect(parseTokens("'hello")).toEqual(["hello"]);
  });

  it("preserves contractions", () => {
    expect(parseTokens("don't can't")).toEqual(["don't", "can't"]);
  });

  it("throws for excessively long text", () => {
    const longText = "a ".repeat(600_000);
    expect(() => parseTokens(longText)).toThrow("Text too long");
  });

  it("tokenises each CJK character separately", () => {
    // Opening of the yuefu poem Jiangnan: every hanzi is its own token and the
    // full-width comma is a punctuation token.
    expect(parseTokens("江南可采莲，莲叶何田田")).toEqual([
      "江",
      "南",
      "可",
      "采",
      "莲",
      "，",
      "莲",
      "叶",
      "何",
      "田",
      "田",
    ]);
  });

  it("keeps full-width CJK punctuation as tokens", () => {
    expect(parseTokens("四是四。十是十！")).toEqual([
      "四",
      "是",
      "四",
      "。",
      "十",
      "是",
      "十",
      "！",
    ]);
  });

  it("splits at the Latin/CJK boundary without touching hanzi", () => {
    expect(parseTokens("AI是cool的")).toEqual(["AI", "是", "cool", "的"]);
  });

  it("repeats identical CJK characters so bigrams can form", () => {
    const model = buildBigramModel(parseTokens("田田"));
    expect(model.getCount("田", "田")).toBe(1);
  });
});

// The fixture is generated by the Rust tokeniser (see the fixture section of
// cli/tests/tokenization_test.rs) and pins parseTokens against it, so the two
// implementations cannot silently drift. If this fails after a Rust-side
// change, port the change here; if it fails after a TS-side change, that
// change diverged from the CLI.
describe("parseTokens agrees with the Rust tokeniser", () => {
  interface FixtureCase {
    input: string;
    tokens: string[];
  }
  const fixturePath = join(
    __dirname,
    "..",
    "..",
    "cli",
    "tests",
    "fixtures",
    "tokenization_cases.json",
  );
  const cases: FixtureCase[] = JSON.parse(readFileSync(fixturePath, "utf-8"));

  it.each(cases)("tokenises $input identically", ({ input, tokens }) => {
    expect(parseTokens(input)).toEqual(tokens);
  });
});

describe("getVocabulary", () => {
  it("returns unique tokens preserving insertion order", () => {
    const tokens = ["the", "cat", "sat", "the", "cat"];
    expect(getVocabulary(tokens)).toEqual(["the", "cat", "sat"]);
  });

  it("returns empty array for empty input", () => {
    expect(getVocabulary([])).toEqual([]);
  });
});

describe("getBigrams", () => {
  it("returns consecutive token pairs", () => {
    expect(getBigrams(["the", "cat", "sat"])).toEqual([
      ["the", "cat"],
      ["cat", "sat"],
    ]);
  });

  it("returns empty array for single token", () => {
    expect(getBigrams(["the"])).toEqual([]);
  });

  it("returns empty array for empty input", () => {
    expect(getBigrams([])).toEqual([]);
  });

  it("includes punctuation in bigrams", () => {
    expect(getBigrams(["cat", ".", "the"])).toEqual([
      ["cat", "."],
      [".", "the"],
    ]);
  });
});

describe("buildBigramModel", () => {
  it("counts bigram occurrences", () => {
    const tokens = parseTokens("the cat sat. the cat mat.");
    const model = buildBigramModel(tokens);

    expect(model.getCount("the", "cat")).toBe(2);
    expect(model.getCount("cat", "sat")).toBe(1);
    expect(model.getCount("cat", "mat")).toBe(1);
    expect(model.getCount("the", "sat")).toBe(0);
  });

  it("reports successors correctly", () => {
    const tokens = parseTokens("the cat sat.");
    const model = buildBigramModel(tokens);

    expect(model.hasSuccessors("the")).toBe(true);
    expect(model.hasSuccessors("cat")).toBe(true);
    expect(model.hasSuccessors(".")).toBe(false);
  });

  it("handles empty tokens", () => {
    const model = buildBigramModel([]);
    expect(model.getCount("a", "b")).toBe(0);
    expect(model.hasSuccessors("a")).toBe(false);
  });
});
