export const PLAYBACK_CONFIG = {
  DICE_ROLL_ANIMATION_MS: 80,
  POST_WRITE_PAUSE_MS: 800,
  DEFAULT_STEP_INTERVAL_MS: 3000,
  MIN_STEP_INTERVAL_MS: 150,
  MAX_STEP_INTERVAL_MS: 6000,
  LOOP_PAUSE_MULTIPLIER: 5,
} as const;
