export const PLAYBACK_CONFIG = {
  TRAINING_DEFAULT_STEP_INTERVAL_MS: 500,
  TRAINING_MIN_STEP_INTERVAL_MS: 50,
  TRAINING_MAX_STEP_INTERVAL_MS: 3000,
  GENERATION_DEFAULT_STEP_INTERVAL_MS: 800,
  GENERATION_MIN_STEP_INTERVAL_MS: 100,
  GENERATION_MAX_STEP_INTERVAL_MS: 5000,
  LOOP_PAUSE_MULTIPLIER: 5,
} as const;
