export const PLAYBACK_CONFIG = {
  DEFAULT_STEP_INTERVAL_MS: 3000,
  MIN_STEP_INTERVAL_MS: 150,
  MAX_STEP_INTERVAL_MS: 15000,
  TRAINING_DEFAULT_STEP_INTERVAL_MS: 500,
  TRAINING_MIN_STEP_INTERVAL_MS: 50,
  TRAINING_MAX_STEP_INTERVAL_MS: 3000,
  LOOP_PAUSE_MULTIPLIER: 5,
} as const;
