#!/usr/bin/env -S uv run --script
# /// script
# requires-python = ">=3.12"
# dependencies = ["boto3>=1.35"]
# ///
"""Manage the Tigris bucket that serves llmsunplugged.org's PDFs.

The booklets, cutouts, sheets, worksheets and presenter guides used to live in
`website/public/` and ship inside the GitHub Pages artifact. They were the
largest and fastest-growing category there and, being committed, they grew
`.git` permanently too (each regeneration landed a fresh multi-MB blob). They
now live in one public Tigris bucket fronted by https://pdf.llmsunplugged.org
--- the same arrangement as slop.university, minus two things it needed and we
don't: the robots.txt here is *permissive* (these are legitimate teaching
materials we want discoverable, not fabricated documents to keep out of
Google Scholar), and there is no CORS (every consumer is a plain download
link; nothing fetches these cross-origin).

The bucket is provisioned with flyctl (which also prints the credentials):

    fly storage create -n llms-unplugged-pdfs --public
    fly storage update llms-unplugged-pdfs --custom-domain pdf.llmsunplugged.org
    # Namecheap: CNAME  pdf -> llms-unplugged-pdfs.t3.tigrisbucket.io.

Credentials come from the untracked `[env]` block in
`~/.config/mise/config.local.toml` (run under `mise exec` or an activated
shell). They are deliberately not named AWS_* so they cannot hijack unrelated
S3 clients:

    LLMSU_PDF_BUCKET            = "llms-unplugged-pdfs"
    LLMSU_S3_ACCESS_KEY_ID      = ...
    LLMSU_S3_SECRET_ACCESS_KEY  = ...
    LLMSU_S3_ENDPOINT           = "https://fly.storage.tigris.dev"  # default

Keys mirror the paths the website links: `booklets/<name>.pdf`,
`cutouts/...`, `sheets/...`, `worksheets/...`,
`decks/<slug>/presenter-guide.pdf`, plus a few root-level one-offs. The
website's single source of truth for what exists is
`website/src/data/pdf-manifest.json`, regenerated by `manifest` from a bucket
listing --- UsingTheSlides.astro and the build's PDF link check both read it,
so an upload isn't finished until `manifest` has run and the JSON is
committed.

Usage:
  ops/bucket-sync.py setup                  # upload robots.txt (idempotent)
  ops/bucket-sync.py upload DIR             # upload a tree; keys relative to DIR
  ops/bucket-sync.py upload --key KEY FILE  # upload one file under an explicit key
  ops/bucket-sync.py manifest               # bucket listing -> pdf-manifest.json
  ops/bucket-sync.py verify [KEY]           # check the served origin
"""

import json
import os
import sys
import urllib.error
import urllib.request
from concurrent.futures import ThreadPoolExecutor
from pathlib import Path

import boto3

PUBLIC_BASE = "https://pdf.llmsunplugged.org"
DEFAULT_ENDPOINT = "https://fly.storage.tigris.dev"
REPO_ROOT = Path(__file__).resolve().parent.parent
MANIFEST_PATH = REPO_ROOT / "website" / "src" / "data" / "pdf-manifest.json"

# The bucket serves teaching materials people should be able to find; kept as
# an explicit file so `verify` can assert the policy rather than infer it.
ROBOTS_TXT = """\
# LLMs Unplugged teaching PDFs (booklets, worksheets, presenter guides).
# Explicitly permissive: these are the downloadable artefacts of
# https://www.llmsunplugged.org and indexing them is wanted.
User-agent: *
Disallow:
"""

# Keys are stable names whose content changes on regeneration (a presenter
# guide keeps its key across rebuilds), so they must not be cached as
# immutable the way slop.university's content-addressed PDFs are.
CACHE_CONTROL = "public, max-age=3600"


def client():
    missing = [
        k
        for k in (
            "LLMSU_PDF_BUCKET",
            "LLMSU_S3_ACCESS_KEY_ID",
            "LLMSU_S3_SECRET_ACCESS_KEY",
        )
        if not os.environ.get(k)
    ]
    if missing:
        sys.exit(
            f"missing bucket credentials in env: {', '.join(missing)}\n"
            "they live in the [env] block of ~/.config/mise/config.local.toml; "
            "run this under `mise exec` or an activated shell"
        )
    return boto3.client(
        "s3",
        endpoint_url=os.environ.get("LLMSU_S3_ENDPOINT", DEFAULT_ENDPOINT),
        aws_access_key_id=os.environ["LLMSU_S3_ACCESS_KEY_ID"],
        aws_secret_access_key=os.environ["LLMSU_S3_SECRET_ACCESS_KEY"],
        region_name="auto",
    )


def bucket_name() -> str:
    return os.environ["LLMSU_PDF_BUCKET"]


def setup() -> None:
    s3 = client()
    s3.put_object(
        Bucket=bucket_name(),
        Key="robots.txt",
        Body=ROBOTS_TXT.encode(),
        ContentType="text/plain; charset=utf-8",
        CacheControl="public, max-age=3600",
    )
    print(f"robots.txt uploaded ({len(ROBOTS_TXT)} bytes, permissive)")


def collect_tree(root: Path) -> list[tuple[Path, str]]:
    """(file, key) pairs for a staged directory: key = path relative to root."""
    pairs = []
    for p in sorted(root.rglob("*")):
        if not p.is_file():
            continue
        if p.suffix != ".pdf":
            sys.exit(f"refusing to upload a non-PDF: {p}")
        pairs.append((p, p.relative_to(root).as_posix()))
    return pairs


def upload(args: list[str]) -> None:
    key = None
    if args and args[0] == "--key":
        if len(args) != 3:
            sys.exit("usage: upload --key KEY FILE")
        key, args = args[1], args[2:]

    if key is not None:
        path = Path(args[0])
        if not path.is_file() or path.suffix != ".pdf":
            sys.exit(f"not a PDF file: {path}")
        if not key.endswith(".pdf"):
            sys.exit(f"key must end in .pdf: {key}")
        pairs = [(path, key)]
    else:
        if len(args) != 1 or not Path(args[0]).is_dir():
            sys.exit("usage: upload DIR  (or: upload --key KEY FILE)")
        pairs = collect_tree(Path(args[0]))
        if not pairs:
            sys.exit(f"nothing to upload under {args[0]}")

    s3 = client()
    bucket = bucket_name()

    def put(pair: tuple[Path, str]) -> str:
        p, k = pair
        s3.upload_file(
            str(p),
            bucket,
            k,
            ExtraArgs={"ContentType": "application/pdf", "CacheControl": CACHE_CONTROL},
        )
        return k

    # Uploads are latency-bound, not CPU-bound.
    with ThreadPoolExecutor(max_workers=8) as pool:
        for i, k in enumerate(pool.map(put, pairs), 1):
            print(f"[{i}/{len(pairs)}] {k}")

    print("\nnow run `ops/bucket-sync.py manifest` and commit the updated manifest")


def manifest() -> None:
    s3 = client()
    keys: list[str] = []
    paginator = s3.get_paginator("list_objects_v2")
    for page in paginator.paginate(Bucket=bucket_name()):
        for obj in page.get("Contents", []):
            if obj["Key"].endswith(".pdf"):
                keys.append(obj["Key"])
    keys.sort()
    MANIFEST_PATH.write_text(json.dumps(keys, indent=2) + "\n")
    print(f"wrote {len(keys)} keys to {MANIFEST_PATH.relative_to(REPO_ROOT)}")


def verify(sample: str | None) -> None:
    """Check the live origin the way a browser and a crawler each would."""
    ok = True

    def fetch(url: str):
        return urllib.request.urlopen(urllib.request.Request(url), timeout=30)

    try:
        body = fetch(f"{PUBLIC_BASE}/robots.txt").read().decode()
        if "Disallow: /" in body:
            print(f"robots.txt: WRONG BODY (expected permissive)\n{body}")
            ok = False
        else:
            print(f"robots.txt: OK ({PUBLIC_BASE}/robots.txt is permissive)")
    except urllib.error.URLError as e:
        print(f"robots.txt: FAILED --- {e}")
        ok = False

    if sample:
        url = f"{PUBLIC_BASE}/{sample}"
        try:
            r = fetch(url)
            ctype = r.headers.get("Content-Type")
            print(f"{sample}: HTTP {r.status}, Content-Type: {ctype}")
            if ctype != "application/pdf":
                print("  Content-Type: FAILED (wanted application/pdf)")
                ok = False
        except urllib.error.URLError as e:
            print(f"{sample}: FAILED --- {e}")
            ok = False

    sys.exit(0 if ok else 1)


def main() -> None:
    argv = sys.argv[1:]
    if not argv:
        sys.exit(__doc__)
    cmd, rest = argv[0], argv[1:]
    if cmd == "setup":
        setup()
    elif cmd == "upload":
        upload(rest)
    elif cmd == "manifest":
        manifest()
    elif cmd == "verify":
        verify(rest[0] if rest else None)
    else:
        sys.exit(f"unknown command: {cmd}\n{__doc__}")


if __name__ == "__main__":
    main()
