import { existsSync, readFileSync } from "node:fs";
import { join } from "node:path";
import manifest from "../../src/data/pdf-manifest.json";
import { PDF_BASE } from "../../src/lib/pdfs";

const manifestKeys = new Set<string>(manifest);

export function extractPdfLinks(html: string): string[] {
  const pdfLinkRegex = /href="([^"]*\.pdf)"/g;
  const links: string[] = [];
  let match;
  while ((match = pdfLinkRegex.exec(html)) !== null) {
    links.push(match[1]);
  }
  return links;
}

export function resolveLinkPath(link: string, htmlFilePath: string, distDir: string): string {
  return link.startsWith("/") ? join(distDir, link) : join(htmlFilePath, "..", link);
}

/**
 * A pdf.llmsunplugged.org link is broken when its key isn't in the committed
 * bucket manifest (src/data/pdf-manifest.json, regenerated by
 * `ops/bucket-sync.py manifest`) --- checkable offline, unlike the bucket
 * itself. Other external hosts are out of scope for this check.
 */
export function isBrokenBucketLink(link: string): boolean {
  return !manifestKeys.has(decodeURI(link.slice(PDF_BASE.length + 1)));
}

export function findBrokenPdfLinks(htmlFiles: string[], distDir: string): string[] {
  const brokenLinks: string[] = [];

  for (const htmlFile of htmlFiles) {
    const content = readFileSync(htmlFile, "utf-8");
    const pdfLinks = extractPdfLinks(content);

    for (const pdfPath of pdfLinks) {
      if (/^https?:\/\//.test(pdfPath)) {
        if (pdfPath.startsWith(`${PDF_BASE}/`) && isBrokenBucketLink(pdfPath)) {
          brokenLinks.push(`${htmlFile}: ${pdfPath} (not in pdf-manifest.json)`);
        }
        continue;
      }
      const resolvedPath = resolveLinkPath(pdfPath, htmlFile, distDir);
      if (!existsSync(resolvedPath)) {
        brokenLinks.push(`${htmlFile}: ${pdfPath}`);
      }
    }
  }

  return brokenLinks;
}
